theme = "github_dark"

[editor]
true-color = true

[keys.normal]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
